apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-fallback
  labels:
    app.kubernetes.io/part-of: ctfpilot
    app.kubernetes.io/name: instance-fallback
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: challenges
    ctfpilot.com/component: instance-fallback

spec:
  # HA setup
  replicas: 3
  selector:
    matchLabels:
      ctfpilot.com/component: instance-fallback

  template:
    metadata:
      labels:
        ctfpilot.com/component: instance-fallback
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: instancing-fallback
          image: ctfpilot/instance-fallback:1.0.0
          imagePullPolicy: Always
          ports:
          - name:  http
            containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: instance-fallback
  labels:
    app.kubernetes.io/part-of: ctfpilot
    app.kubernetes.io/name: instance-fallback
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: challenges
    ctfpilot.com/component: instance-fallback
spec:
  selector:
    ctfpilot.com/component: instance-fallback
  ports:
  - name: http
    port: 80
    targetPort: http
