name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Release
    if: github.repository == 'ctfpilot/instancing-fallback'
    environment: Release
    uses: the0mikkel/ci/.github/workflows/semver-release-standalone.yml@v1.4.1
    with:
      ENVIRONMENT: Release
      RELEASE_GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}

  docker:
    name: Docker build and push
    needs:
      - release
    uses: the0mikkel/ci/.github/workflows/docker.yml@v1.4.0
    if: github.repository == 'ctfpilot/instancing-fallback' && (needs.release.outputs.version != '' && needs.release.outputs.version != null)
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      semver: ${{ needs.release.outputs.version }}
      arguments: |
        VERSION=${{ needs.release.outputs.version }}
