name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Release
    uses: ctfpilot/ci/.github/workflows/release.yml@v1.1.1
    secrets:
      RELEASE_GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
    with:
      repository: ctfpilot/instancing-fallback
      ENVIRONMENT: Release

  docker:
    name: Docker build and push
    needs:
      - release
    uses: ctfpilot/ci/.github/workflows/docker.yml@v1.1.1
    if: needs.release.outputs.version != '' && needs.release.outputs.version != null
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repository: ctfpilot/instancing-fallback
      semver: ${{ needs.release.outputs.version }}
      arguments: |
        VERSION=${{ needs.release.outputs.version }}

  update-develop:
    if: github.ref == 'refs/heads/main'
    name: "Update Develop Branch"
    needs:
      - release
    uses: ctfpilot/ci/.github/workflows/develop-update.yml@v1.2.0
    permissions:
      contents: read
      pull-requests: write
      issues: write
    with:
      repository: ctfpilot/instancing-fallback
